# Generated by Django 6.1.1 on 2026-10-02 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        max_length=32,
                        unique=True,
                        verbose_name="Идентификатор категории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="categories/",
                        verbose_name="Изображение категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=256, verbose_name="Название продукта"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        max_length=32,
                        unique=True,
                        verbose_name="Идентификатор продукта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(verbose_name="Цена продукта"),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        verbose_name="Название подкатегории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        max_length=32,
                        unique=True,
                        verbose_name="Идентификатор подкатегории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="subcategories/",
                        verbose_name="Изображение подкатегории",
                    ),
                ),
            ],
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "Подкатегории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ShoppingBasket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Количество продукта в корзине",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "корзина",
                "verbose_name_plural": "Корзины",
                "ordering": ("user",),
            },
        ),
    ]
