# Generated by Django 6.1.1 on 2026-10-02 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Количество продукта в корзине",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт в корзине",
                "verbose_name_plural": "Продукты в корзине",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingbasket",
            options={"verbose_name": "корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.RemoveConstraint(
            model_name="shoppingbasket",
            name="unique_user_product_in_basket",
        ),
        migrations.AddField(
            model_name="basketproduct",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_items",
                to="products.shoppingbasket",
                verbose_name="Корзина",
            ),
        ),
        migrations.AddField(
            model_name="basketproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_items",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="shoppingbasket",
            name="products",
            field=models.ManyToManyField(
                related_name="baskets",
                through="products.BasketProduct",
                to="products.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.RemoveField(
            model_name="shoppingbasket",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="shoppingbasket",
            name="product",
        ),
        migrations.AddConstraint(
            model_name="basketproduct",
            constraint=models.UniqueConstraint(
                fields=("basket", "product"), name="unique_basket_product"
            ),
        ),
    ]
