# Generated by Django 6.1.1 on 2026-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_basketproduct_alter_shoppingbasket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_large",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to="products/large/",
                verbose_name="Большой размер (1000×1000)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_medium",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to="products/medium/",
                verbose_name="Средний размер (400×400)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to="products/thumb/",
                verbose_name="Миниатюра (150×150)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                upload_to="categories/", verbose_name="Изображение категории"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="products/original/", verbose_name="Изображение продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                upload_to="subcategories/", verbose_name="Изображение подкатегории"
            ),
        ),
    ]
